/* Create imports */

/* Create controllers */
exports.generateReview = async (req, res) => {
  try {
    res.status(200).json({ msg: "Review generated by AI" });
  } catch (error) {
    console.error(error.message);
    res.status(500).json({ error: error.message });
  }
};
